### ISSUE TITLE
Plugin não é ativado em ambiente LINUX Ubuntu 20

### ISSUE THREAD

**Issue by HumbertoDiego** [dsgoficial/ferramentas_edicao#25]
MENSAGEM DE ERRO:
Impossível carregar complemento 'ferramentas_edicao' Devido a um erro ao chamar o método Class Factory(). 

TypeError: 'type' object is not subscriptable 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ferramentas_edicao/_init_.py", line 7, in classFactory
    from .editionPlugin import EditionPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ferramentas_edicao/editionPlugin.py", line 9, in 
    from .controllers.mapBuilderController import MapBuildController
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ferramentas_edicao/controllers/mapBuilderController.py", line 12, in 
    from ..factories.compositionSingleton import CompositionSingleton
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ferramentas_edicao/factories/compositionSingleton.py", line 11, in 
    class CompositionSingleton:
  File "/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/ferramentas_edicao/factories/compositionSingleton.py", line 107, in CompositionSingleton
    def insertCompositions(self, compositionToUpdate: QgsPrintLayout, qptsToInsert: list[dict]):
TypeError: 'type' object is not subscriptable

Versão do Python: 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0] 
Versão do QGIS: 3.24.3-Tisler Tisler, cf22b74e01 

Caminho do Python:
/usr/share/qgis/python
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/SAP/../
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/SAP/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/SAP/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/SAP/Login/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/SAP/Login/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/SAP/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/Tools/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/Tools/LoadData/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/Tools/LoadData/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/SAP/../SAP/../
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/SAP/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/SAP/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/SAP/Login/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/SAP/Login/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/SAP/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/Database/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/Tools/Routines/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/Tools/Routines/../
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/Tools/Routines/../
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/Tools/Routines/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/Tools/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/Tools/Menu/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/Tools/Menu/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/Tools/Menu/../
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/Tools/Menu/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/Tools/LoadData/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/Tools/LoadData/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/Validate/Operations/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/Validate/Operations/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/Validate/Operations/..
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/Ferramentas_Producao/Validate/..
.
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DSGTools_Op/QuickGeocoder/dependencies
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DsgTools
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DSGTools_Op/QuickGeocoder/dependencies
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DSGTools_Op/auxiliar
/home/dgeo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DSGTools_Op/QuickGeocoder/dependencies

https://www.datasciencelearner.com/typeerror-type-object-is-not-subscriptable-fix/

**Comment by dinizime** [comment]
Talvez seja algo específico de como o Linux compila a verificação de tipos do python novo. 
Eu atualizei pro padrão mais "correto" de tipos no ultimo commit, poderia testar se corrigiu?

**Comment by HumbertoDiego** [comment]
Corrigiu!

Tava tentando fazer o QGIS usar python3.9 mas talvez desse outros bugs.

Infelizmente deu outro tipo de erro,  _ModuleNotFoundError: No module named 'shapely'_ vou postar separado.
Obrigado.
