### ISSUE TITLE
BUG no preparo da carta OrtoImagem quando adicioanada as classes infra_pista_pouso_p e llp_aglomerado_rual_p

### ISSUE THREAD

**Issue by HumbertoDiego** [dsgoficial/ferramentas_edicao#27]
Versão do QGIS: 3.24.3-Tisler
Código de revisão do QGIS: cf22b74e
Versão do Qt: 5.15.3
Versão do Python: 3.9.5
Versão do GDAL: 3.4.3
Versão do GEOS: 3.10.2-CAPI-1.16.0
Versão do PROJ: Rel. 9.0.0, March 1st, 2022
Versão PDAL: 2.3.0 (git-version: 0a6ef5)
Algoritmo iniciado as: 2022-07-07T10:53:17
Algoritmo 'Prepara carta ortoimagem' iniciando…
Entrada de parâmetros:
{ 'INPUT_FRAME' : 'dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."aux_moldura_a" (geom) sql=id in (SELECT id FROM ONLY "edgv"."aux_moldura_a")', 'INPUT_LAYERS' : ['dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."aquisicao_centroide_elemento_hidrografico_p" (geom) sql=id in (SELECT id FROM ONLY "edgv"."aquisicao_centroide_elemento_hidrografico_p")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."aquisicao_centroide_ilha_p" (geom) sql=id in (SELECT id FROM ONLY "edgv"."aquisicao_centroide_ilha_p")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."aquisicao_centroide_limite_especial_p" (geom) sql=id in (SELECT id FROM ONLY "edgv"."aquisicao_centroide_limite_especial_p")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."aquisicao_centroide_massa_dagua_p" (geom) sql=id in (SELECT id FROM ONLY "edgv"."aquisicao_centroide_massa_dagua_p")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."aquisicao_limite_elemento_hidrografico_l" (geom) sql=id in (SELECT id FROM ONLY "edgv"."aquisicao_limite_elemento_hidrografico_l")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."aquisicao_limite_limite_especial_l" (geom) sql=id in (SELECT id FROM ONLY "edgv"."aquisicao_limite_limite_especial_l")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."aquisicao_limite_massa_dagua_l" (geom) sql=id in (SELECT id FROM ONLY "edgv"."aquisicao_limite_massa_dagua_l")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."aux_area_sem_dados_a" (geom) sql=id in (SELECT id FROM ONLY "edgv"."aux_area_sem_dados_a")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."aux_moldura_a" (geom) sql=id in (SELECT id FROM ONLY "edgv"."aux_moldura_a")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."aux_moldura_area_continua_a" (geom) sql=id in (SELECT id FROM ONLY "edgv"."aux_moldura_area_continua_a")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."aux_revisao_a" (geom) sql=id in (SELECT id FROM ONLY "edgv"."aux_revisao_a")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."aux_revisao_l" (geom) sql=id in (SELECT id FROM ONLY "edgv"."aux_revisao_l")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."aux_revisao_p" (geom) sql=id in (SELECT id FROM ONLY "edgv"."aux_revisao_p")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."aux_validacao_a" (geom) sql=id in (SELECT id FROM ONLY "edgv"."aux_validacao_a")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."aux_validacao_l" (geom) sql=id in (SELECT id FROM ONLY "edgv"."aux_validacao_l")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."aux_validacao_p" (geom) sql=id in (SELECT id FROM ONLY "edgv"."aux_validacao_p")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."cobter_massa_dagua_a" (geom) sql=id in (SELECT id FROM ONLY "edgv"."cobter_massa_dagua_a")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."constr_extracao_mineral_a" (geom) sql=id in (SELECT id FROM ONLY "edgv"."constr_extracao_mineral_a")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."constr_extracao_mineral_p" (geom) sql=id in (SELECT id FROM ONLY "edgv"."constr_extracao_mineral_p")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."edicao_identificador_trecho_rod_p" (geom) sql=id in (SELECT id FROM ONLY "edgv"."edicao_identificador_trecho_rod_p")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."edicao_simb_cota_mestra_l" (geom) sql=id in (SELECT id FROM ONLY "edgv"."edicao_simb_cota_mestra_l")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."edicao_simb_torre_energia_p" (geom) sql=id in (SELECT id FROM ONLY "edgv"."edicao_simb_torre_energia_p")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."edicao_texto_generico_l" (geom) sql=id in (SELECT id FROM ONLY "edgv"."edicao_texto_generico_l")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."edicao_texto_generico_p" (geom) sql=id in (SELECT id FROM ONLY "edgv"."edicao_texto_generico_p")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."elemnat_curva_nivel_l" (geom) sql=id in (SELECT id FROM ONLY "edgv"."elemnat_curva_nivel_l")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."elemnat_elemento_hidrografico_a" (geom) sql=id in (SELECT id FROM ONLY "edgv"."elemnat_elemento_hidrografico_a")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."elemnat_elemento_hidrografico_l" (geom) sql=id in (SELECT id FROM ONLY "edgv"."elemnat_elemento_hidrografico_l")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."elemnat_elemento_hidrografico_p" (geom) sql=id in (SELECT id FROM ONLY "edgv"."elemnat_elemento_hidrografico_p")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."elemnat_ilha_a" (geom) sql=id in (SELECT id FROM ONLY "edgv"."elemnat_ilha_a")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."elemnat_ilha_p" (geom) sql=id in (SELECT id FROM ONLY "edgv"."elemnat_ilha_p")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."elemnat_ponto_cotado_p" (geom) sql=id in (SELECT id FROM ONLY "edgv"."elemnat_ponto_cotado_p")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."elemnat_terreno_sujeito_inundacao_a" (geom) sql=id in (SELECT id FROM ONLY "edgv"."elemnat_terreno_sujeito_inundacao_a")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."elemnat_toponimo_fisiografico_natural_l" (geom) sql=id in (SELECT id FROM ONLY "edgv"."elemnat_toponimo_fisiografico_natural_l")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."elemnat_toponimo_fisiografico_natural_p" (geom) sql=id in (SELECT id FROM ONLY "edgv"."elemnat_toponimo_fisiografico_natural_p")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."elemnat_trecho_drenagem_l" (geom) sql=id in (SELECT id FROM ONLY "edgv"."elemnat_trecho_drenagem_l")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."infra_barragem_a" (geom) sql=id in (SELECT id FROM ONLY "edgv"."infra_barragem_a")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."infra_barragem_l" (geom) sql=id in (SELECT id FROM ONLY "edgv"."infra_barragem_l")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."infra_elemento_energia_a" (geom) sql=id in (SELECT id FROM ONLY "edgv"."infra_elemento_energia_a")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."infra_elemento_energia_l" (geom) sql=id in (SELECT id FROM ONLY "edgv"."infra_elemento_energia_l")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."infra_elemento_energia_p" (geom) sql=id in (SELECT id FROM ONLY "edgv"."infra_elemento_energia_p")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."infra_elemento_infraestrutura_a" (geom) sql=id in (SELECT id FROM ONLY "edgv"."infra_elemento_infraestrutura_a")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."infra_elemento_infraestrutura_l" (geom) sql=id in (SELECT id FROM ONLY "edgv"."infra_elemento_infraestrutura_l")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."infra_elemento_infraestrutura_p" (geom) sql=id in (SELECT id FROM ONLY "edgv"."infra_elemento_infraestrutura_p")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."infra_ferrovia_l" (geom) sql=id in (SELECT id FROM ONLY "edgv"."infra_ferrovia_l")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."infra_obstaculo_vertical_p" (geom) sql=id in (SELECT id FROM ONLY "edgv"."infra_obstaculo_vertical_p")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."infra_pista_pouso_a" (geom) sql=id in (SELECT id FROM ONLY "edgv"."infra_pista_pouso_a")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."infra_pista_pouso_l" (geom) sql=id in (SELECT id FROM ONLY "edgv"."infra_pista_pouso_l")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."infra_pista_pouso_p" (geom) sql=id in (SELECT id FROM ONLY "edgv"."infra_pista_pouso_p")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."infra_via_deslocamento_l" (geom) sql=id in (SELECT id FROM ONLY "edgv"."infra_via_deslocamento_l")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."llp_aglomerado_rural_p" (geom) sql=id in (SELECT id FROM ONLY "edgv"."llp_aglomerado_rural_p")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."llp_area_pub_militar_a" (geom) sql=id in (SELECT id FROM ONLY "edgv"."llp_area_pub_militar_a")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."llp_area_pub_militar_l" (geom) sql=id in (SELECT id FROM ONLY "edgv"."llp_area_pub_militar_l")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."llp_limite_legal_l" (geom) sql=id in (SELECT id FROM ONLY "edgv"."llp_limite_legal_l")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."llp_localidade_p" (geom) sql=id in (SELECT id FROM ONLY "edgv"."llp_localidade_p")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."llp_nome_local_p" (geom) sql=id in (SELECT id FROM ONLY "edgv"."llp_nome_local_p")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."llp_terra_indigena_a" (geom) sql=id in (SELECT id FROM ONLY "edgv"."llp_terra_indigena_a")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."llp_terra_indigena_l" (geom) sql=id in (SELECT id FROM ONLY "edgv"."llp_terra_indigena_l")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."llp_unidade_conservacao_a" (geom) sql=id in (SELECT id FROM ONLY "edgv"."llp_unidade_conservacao_a")','dbname=\'PIT2022_cartaortoimagem_100k_AM_31973_MI0129\' host=postgresql4cgeo port=5432 user=\'user\' password=\'senha\' key=\'id\' selectatid=false checkPrimaryKeyUnicity=\'1\' table="edgv"."llp_unidade_conservacao_l" (geom) sql=id in (SELECT id FROM ONLY "edgv"."llp_unidade_conservacao_l")'], 'OUTPUT' : 'TEMPORARY_OUTPUT', 'SCALE' : 2 }

**_Traceback (most recent call last):
File "C:\Users/Administrador/AppData/Roaming/QGIS/QGIS3\profiles\3.24-default/python/plugins\ferramentas_edicao\modules\processings\prepareOrtho.py", line 281, in processAlgorithm
self.setDefaultAttrV2(lyr, valuesToCommit)
File "C:\Users/Administrador/AppData/Roaming/QGIS/QGIS3\profiles\3.24-default/python/plugins\ferramentas_edicao\modules\processings\prepareOrtho.py", line 473, in setDefaultAttrV2
elif feat.attribute(key) == NULL or feat.attribute(key) == 9999 or str(feat.attribute(key)).strip() == '':
KeyError: 'visivel'_**

Execution failed after 7.26 segundos

Carregando camada resultante
Algoritmo 'Prepara carta ortoimagem' finalizado

**Comment by HumbertoDiego** [comment]
### Resolvido ao criar o campo "visível" nas respectivas tabelas.

**Comment by dinizime** [comment]
Como a metodologia ainda está em desenvolvimento pelo grupo de trabalho de carta ortoimagem estão havendo alterações na modelagem da EDGV 3.0 Orto.

A versão mais recente pode ser acessada em
https://github.com/dsgoficial/modelagens
