### ISSUE TITLE
Problema de "alternar rótulo"

### ISSUE THREAD

**Issue by duartetopo** [dsgoficial/ferramentas_edicao#28]
Foi verificado na nova versão do Plugin as poucas opções  pré-configuradas de posições de rótulo. Isso ocorreu na mudança de posição dos valores dos pontos cotados, com isso tiveram que ser alterados manualmente os valores de label_x e y.

**Comment by dinizime** [comment]
Acho que vi o erro aqui, poderia verificar novamente?
