### ISSUE TITLE
Correção placeBorderOfHydrographicElement.py

### ISSUE THREAD

**Issue by matheusfields** [dsgoficial/ferramentas_edicao#49]
Atualmente o processing não está adicionando feições para Recife na camada edicao_borda_elemento_hidrografico_l.

- Com restrições*, o problema se resolve incluindo à linha 61, os valores para **recife contiguo** e **recife afastado**:
```
self.mappingDict = {8: 1, # rocha em agua
                            18: 2, # recife contiguo
                            19: 2 # recife afastado**
        }
```

- *Observação: o processing só gera resultado caso o usuário selecione as feições em que ele deseja gerar as bordas e marque a caixa "Executar somente nas feições selecionadas".

**Comment by MarcelFernandesCGEO** [comment]
- Realizada a alteração sugerida conforme PR
- Corrigido o comportamento de funcionamento em Apenas Selecionados, agora funcional em todas também no caso de todas as feições.
